name: Build EXE

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile keystroke_melody.py --name keystroke_melody

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: keystroke_melody_exe
          path: dist/keystroke_melody.exe

      - name: Attach to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/keystroke_melody.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
